import 'package:tourism_app/tourism.dart';

var tourismList = [
  Tourism(name : 'Tugu Yogyakarta',
  address: 'Gowongan, Kec. Jetis, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55233',
  description: 'Tugu Yogyakarta pada jaman dahulu memiliki ketinggian yang lebih tinggi, sekitar 25 meter dengan puncaknya yang membulat. Nama monumen tersebut pada jaman dahulu sebenarnya bukan Tugu Yogyakarta sebagaimana yang dikenal saat ini. Namanya dulu adalah Golong Giling yang menggambarkan bentuknya Tugu pada jaman dahulu yaitu tiangnya berbentuk silinder atau dalam bahasa jawa disebut Golong dan puncaknya yang bulat yaitu Gilig.',
  scedule: '06.00-17.00',
  ticket: 'free',
  photo: 'assets/img/tugu.jpg',
  imgurl: ['https://ayoyogya.com/images-jogjakarta/post/articles/2020/12/15/41707/tugu.jpg',
    'https://media.suara.com/pictures/653x366/2020/12/15/92671-kawasan-tugu-pal-putih-sudah-bebas-dari-kabel-kabel-di-udara-selasa-15122020.jpg']
  ),
  Tourism(name : 'Candi Borobudur',
      address: 'Kecamatan Borobudur, sekitar 3 km dari Kota Mungkid (ibukota Kabupaten Magelang, Jawa Tengah)',
      description: 'Borobudur dibangun dengan gaya Mandala yang mencerminkan alam semesta dalam kepercayaan Buddha. Struktur bangunan ini berbentuk kotak dengan empat pintu masuk dan titik pusat berbentuk lingkaran. Jika dilihat dari luar hingga ke dalam terbagi menjadi dua bagian yaitu alam dunia yang terbagi menjadi tiga zona di bagian luar, dan alam Nirwana di bagian pusat.',
      scedule: '06.00-17.00',
      ticket: 'Rp25.000,00-Rp75.000,00',
      photo: 'assets/img/borobudur.jpg',
      imgurl: ['https://borobudurpark.com/wp-content/uploads/2017/05/Borobudur-000110-300x200.jpg',
        'https://borobudurpark.com/wp-content/uploads/2017/05/Borobudur-000156-1-300x200.jpg']
  ),
  Tourism(name : 'Candi Prambanan',
      address: 'Gowongan, Kec. Jetis, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55233',
      description: 'Candi Prambanan merupakan candi Hindu yang terbesar di Indonesia. Sampai saat ini belum dapat dipastikan kapan candi ini dibangun dan atas perintah siapa, namun kuat dugaan bahwa Candi Prambanan dibangun sekitar pertengahan abad ke-9 oleh raja dari Wangsa Sanjaya, yaitu Raja Balitung Maha Sambu.',
      scedule: '06.00-17.00',
      ticket: 'Rp10.000,00',
      photo: 'assets/img/prambanan.jpg',
      imgurl: ['https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Yogyakarta_Indonesia_Prambanan-temple-complex-02.jpg/300px-Yogyakarta_Indonesia_Prambanan-temple-complex-02.jpg',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Prambanan_at_night.jpg/220px-Prambanan_at_night.jpg']
  ),
  Tourism(name : 'Pantai Parangtritis',
      address: ' Desa Parangtritis, Kecamatan Kretek, Kabupaten Bantul, Yogyakarta.',
      description: 'Pantai Parangtritis merupakan destinasi wisata pantai yang populer di antara pantai-pantai lainnya di Yogyakarta. Pantai yang terkenal dengan mitos Nyi Roro Kidul tersebut berjarak 25 km dari pusat kota. Objek wisata ini menjadi salah satu yang mendapat kunjungan tertinggi di Yogyakarta.',
      scedule: '24 jam',
      ticket: 'Rp 10.000,00',
      photo: 'assets/img/parangtritis.jpg',
      imgurl: ['https://travelspromo.com/wp-content/uploads/2019/07/Payung-payung-besar-warna-warni-berderet-rapi-dimanfaatkan-sebagai-tempat-berteduh-dan-bersantai-bagi-wisatawan-Pantai-Parangtritis-Arwan-F-640x485.jpg',
        'https://travelspromo.com/wp-content/uploads/2019/07/Berjalan-jalan-menikmati-tepian-laut-Pantai-Parangtritis-Bantul-yang-berpasir-dengan-berkuda-amalia-novitasari-e1565249428795-640x479.jpg']
  ),
  Tourism(name : 'Bukit Bintang',
      address: ' Area Kebun, Srimulyo, Kec. Patuk, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55792',
      description: 'Bukit Bintang Jogja ini menawarkan panorama alam yang sungguh luar biasa, karena sesuai dengan namanya ketika anda sedang berada di kawasan ini seolah-olah anda berada di angkasa dimana bisa melihat gemerlapnya bintang bintang  yang sebenarnya adalah lampu-lampu kota yang bila dilihat dari atas akan terlihat seperti bintang-bintang yang bertebaran di angkasa.',
      scedule: '24 jam',
      ticket: 'Rp 5.000,00',
      photo: 'assets/img/bukitbintang.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/05/lokasi-bukit-bintang-jogja-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/05/foto-bukit-bintang-jogja-451x257.jpg']
  ),
  Tourism(name : 'Gandola Pantai Timang',
      address: 'Jl. Pantai Sel. Jawa, Pantai, Purwodadi, Tepus, Kabupaten Gunung Kidul, Daerah Istimewa Yogyakarta 55881.',
      description: 'Pantai Timang letaknya cukup jauh dari perkotaan. Kamu harus ke kawasan Gunung Kidul di provinsi Daerah Istimewa Yogyakarta untuk menemukan Pantai Timang ini. Ciri khas pantai ini adalah kereta gantung (gondola) berbahan kayu yang menghubungkan Pantai Timang dengan Pulau Timang yang jaraknya cukup jauh. Dahulu gondola itu adalah salah sat ukases yang dibuat oleh masyarakat sekitar khuusnya para nelayan untuk memburu lobster yang ada di pulau timang.',
      scedule: '06.00-17.00',
      ticket: ' Rp. 2000,00- Rp. 5000,00',
      photo: 'assets/img/timang.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2020/03/Gondola-Pantai-Timang-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2020/03/rute-menuju-gondola-pantai-timang-451x257.jpg']
  ),
  Tourism(name : 'Pantai Glagah',
      address: 'Kecamatan Temon, Kabupaten Gunungkidul, Daerah Istimewa Yogyakarta.',
      description: 'Pantai Glagah sendiri merupakan salah satu destinasi wisata favorit di Kulon Progo atau bahkan bisa dibilang sebagai icon kota ini, meskipun beberapa tahun terakhir ini banyak destinasi wisata baru di Kulon Progo seperti Kedung Pedut, Kalibiru, dan masih banyak lagi, tetapi pesona Pantai Glagah tetap menjadi Primadona di kota ini.',
      scedule: '06.00-17.00',
      ticket: 'Rp. 5.000,00',
      photo: 'assets/img/glagah.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2019/08/pantai-glagah-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2019/08/rute-pantai-glagah-451x257.jpg']
  ),
  Tourism(name : 'Puncak Becici',
      address: 'Dusun Gunung Cilik, Desa Gunung Muntuk, Kecamatan Dlingo, Kabupaten Bantul, Yogyakarta dan wilayahnya masuk dalam RPH (Resort Pengelolaan Hutan) Mangunan, wilayah kerja Dishutbun Provinsi Yogyakarta.',
      description: 'Nama Beicici berasal dari gabungan kata “ambeg’ yang mempunyai arti berdiam diri dan kata suci, dua kata tersebut merujuk pada cerita turun temurun yang dipercayai masyarakat setempat. Cerita tersebut tentang putra pendiri Desa Muntuk yang bertapa di bukit barat hutan pinus dan kemudian dia ingin disemayamkan di bukit yang sama ketika meninggal dunia.',
      scedule: '06.00-17.00',
      ticket: ' Rp 2.500,00',
      photo: 'assets/img/becici.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/11/Puncak-Becici-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/11/Harga-Tiket-Puncak-Becici-451x257.jpg']
  ),
  Tourism(name : 'Bukit Lintang Sewu',
      address: 'Desa Muntuk, Kecamatan Dlingo, Kabupaten Bantul, Yogyakarta. ',
      description: 'Pemandangan alam yang tidak kalah mempesona membuat Bukit Langit Sewu ini menjadi tempat favorit bagi pecinta alam. Pada saat menuju bukit, pengunjung akan disuguhkan dengan pepohonan pinus, tetapi saat sampai pengunjung akan disuguhkan panorama hutan Kayu Putih yang menjadi keunikan tempat wisata ini. Diatas pohon Kayu Putih ini juga terdapat Burung Alap-alap yang melintas diatas pohonnya. ',
      scedule: '06.00-17.00',
      ticket: 'RP 2.000,00',
      photo: 'assets/img/lintangsewu.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/11/Bukit-Lintang-Sewu-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/11/Fasilitas-Bukit-Lintang-Sewu-451x257.jpg']
  ),
  Tourism(name : 'Kali Biru',
      address: 'Desa Hargowilis, Kecamatan Kokap, Kulon Progo, Yogyakarta. ',
      description: 'Wisata Alam Kalibiru ini berada pada ketinggian 450 M dpl. Pemandangan alamnya yang sangat indah dan suhu udara yang sangat sejuk karena belum tercemar oleh polusi udara menjadi salah satu daya tarik kawasan wisata alam ini.',
      scedule: '06.00-17.00',
      ticket: 'Rp 5.000,00-Rp 10.000,00',
      photo: 'assets/img/kalibiru.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/10/Lokasi-Kalibiru-1-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/10/Rute-menuju-Kalibiru-1-451x257.jpg']
  ),
  Tourism(name : 'Air Terjun Kembang Soka',
      address: 'Desa Jatimulyo, Kecamatan Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta.',
      description: 'Air Terjun Kembang Soka merupakan air terjun yang berada di lembah sungai Perbukitan Menoreh, air terjun yang disebut – sebut sebagai salah satu surga yang tersembunyi ini mempunyai keindahan yang tak kalah dengan air terjun lain yang ada di di Kulon Progo maupaun Yogyakarta. Kesegaran air sungai khas pegunungan sangat cocok bagi sobat semua yang sudah jenuh dengan hiruk pikuk perkotaan, selain itu udara di tempat ini juga masih sangat segar karena lokasinya yang jauh dari hiruk pikuk perkotaan.',
      scedule: '06.00-17.00',
      ticket: 'Rp. 10.000,00',
      photo: 'assets/img/soka.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2019/09/AIR-TERJUN-KEMBANG-SOKA-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2019/09/RUTE-MENUJU-AIR-TERJUN-KEMBANG-SOKA-451x257.jpg']
  ),
  Tourism(name : 'Air Terjun Luweng Sampang',
      address: 'Desa Sampang, Kecamatan Gedangsari, Kabupaten Gunungkidul, Daerah Istimewa Yogyakarta.',
      description: 'Asal usul dari penamaan Luweng Sampang ini diambil dari bahasa Jawa luweng yang mempunyai arti lubang dan sedangkan sampang yang merupakan lokasi dari keberadaan air terjun ini. Air terjun ini sendiri hanya berketinggian lima meter dengan debit air yang lumayan rendah. Keindahan dari Air Terjun Luweng Sampang ini berganti dan berubah sesuai dengan musim. Saat mengunjungi kawasan wisata ini pada saat musim hujan, debit air akan sangat besar dan juga warna coklat dari tanah juga akan ikut menghiasi keindahan dan kecantikan dari air terjun ini.',
      scedule: '06.00-17.00',
      ticket: ' Rp 2.000,00- Rp 5.000,00',
      photo: 'assets/img/luweng.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2019/01/Fasilitas-Air-Terjun-Luweng-Sampang-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2019/01/Air-Terjun-Luweng-Sampang-451x257.jpg']
  ),
  Tourism(name : 'Hutan Pinus Mangunan',
      address: 'Hutan Pinus, Sukorame, Mangunan, Imogiri, Bantul, Daerah Istimewa Yogyakarta.',
      description: 'Hutan yang berada di kabupaten Bantul ini menawarkan pesona yang menarik dan membuat suasana tenang dan damai. Untuk menikmati sejuknya udara di Hutan Pinus Mangunan ini sebaiknya datang pada pagi hari. Ketika tiba di hutan tersebut anda akan melihat pepohonan yang berdiri dengan kokoh. Dengan suasana yang tenang dan suara gesekan daun-daun yang melambai-lambai diterpa angin. Semakin anda melihat-lihat anda akan menjumpai pepohonan pinus yang tumbuh dengan rindang.',
      scedule: '06.00-17.00',
      ticket: ' Rp 2.500,00',
      photo: 'assets/img/mangunan.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/11/lokasi-hutan-pinus-mangunan-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/11/harga-tiket-hutan-pinus-mangunan-451x257.png']
  ),
  Tourism(name : 'Hutan Pinus Pengger',
      address: 'Desa Terong, Kecamatan Dlingo, Kabupaten Bantul, Daerah Istimewa Yogyakarta.',
      description: 'Hutan Pinus Pengger ini adalah efek positif atas keberhasilan pendahulunya yaitu Hutan Pinus Asri yang juga berada dalam satu kawasan di daerah Dlingo Bantul Yogyakarta, kreativitas masyarakat sekitar mengembangkan Hutan Pinus Pengger menjadi destinasi wisata pun berbuah manis, pengelola pun menyadari harus terdapat pembeda antara hutan pinus satu dengan lainnya agar menjadi daya tarik tersendiri bagi wisatawan.',
      scedule: '06.00-17.00',
      ticket: 'Rp2.500,00',
      photo: 'assets/img/pengger.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/01/lokasi-hutan-pinus-pengger-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/01/rute-hutan-pinus-pengger-451x257.jpg']
  ),
  Tourism(name : 'Seribu Batu Songgo Langit',
      address: 'Jalan Hutan Pinus Nganjir, Mangunan, Dlingo, Bantul, Daerah Istimewa Yogyakarta 55783.',
      description: 'Nama Seribu Batu Songgo Langit memiliki makna tersendiri. Sebelum jadi tempat wisata, di lokasi ini terdapat ratusan bahkan ribuan batu dan pastinya hutan pinus. Songgo langit berarti penyangga langit, hal ini dikarenakan di Seribu Baru Songgo Langit terdapat bukit yang seakan akan merupakan tiang dari langit .Seribu Batu Songgo Langit merupakan tempat wisata di kawasan Dlingo yang menawarkan berbagai macam atraksi wisata, namun kebanyakan adalah spot foto.',
      scedule: '06.00-17.00',
      ticket: 'Rp 2.500,00',
      photo: 'assets/img/songgo.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/04/lokasi-seribu-batu-songgo-langit-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/04/rute-seribu-batu-songgo-langit-451x257.jpg']
  ),
  Tourism(name : 'Wisata Kraton Jogja',
      address: ' lokasi Kraton Jogja ini berada di selatan dari Jalan paling terkenal di wilayah Yogyakarta yaitu Jalan Malioboro',
      description: 'Kraton Jogja adalah sebuah komplek kerajaan yang berada tepat berdiri di tengah kota Yogyakarta. Kraton yang didirikan seiring perjanjian giyanti pada tahun 1755 yang memecah Kerajaan Mataram Islam menjadi Kerajaan Ngayogyakarta Surakarta ini menyimpan keindahan arsitektur jawa yang tidak diragukan lagi, dan merupakan salah komplek istana terbaik di tanah jawa.',
      scedule: '06.00-17.00',
      ticket: 'Rp 5.000,00',
      photo: 'assets/img/kraton.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/05/lokasi-wisata-kraton-jogja-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/05/fasititas-wisata-kraton-jogja-451x257.jpg']
  ),
  Tourism(name : 'Pasar Beringharjo',
      address: 'Jln. Malioboro, Kelurahan Ngupasan, Kecamatan Gondomanan, Kota Yogyakarta.',
      description: 'Di Pasar Beringharjo ini dari mulai pintu gerbang utama yang berada tepat di sisi selatan Jalan Malioboro anda akan menemukan pedagang kuliner yang menjajakan kuliner tradisional seperti Brem Bulat khas Jogja yang memiliki tekstur lembut, Krasikan yaitu semacam dodol yang bahan utamanya berasal dari tepung beras, gula jawa, dan hancuran wijen. Pastel, Risoles, Kroket, Bakpia khas Yogyakarta, Hung Kwe maupun Nagasari yang terkenal memiliki rasa manis yang lembut.',
      scedule: '06.00-17.00',
      ticket: 'Rp 5.000,00',
      photo: 'assets/img/beringharjo.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/05/Wisata-Pasar-Beringharjo-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/05/Rute-Meuju-Pasar-Beringharjo-451x257.jpg']
  ),
  Tourism(name : 'Titik 0 (Nol) Jogja',
      address: 'Ngupasan, Gondomanan, Daerah Istimewa Yogyakarta.',
      description: 'Titik 0 Kilometer Yogyakarta memang tempat favorit wisatawan untuk menghabiskan waktu, terlebih pada sore hari dan malam hari yang setiap hari selalu ramai disesaki oleh para wisatawan yang sekedar hanya untuk nongkrong di dudukan yang banyak disediakan di sekitar perempatan.Memang tempat ini bukanlah perempatan pada umumnya yang biasanya hanya terdiri dari lampu lalu lintas dan kendaraan yang berhenti. Namun di Titik Nol Jogja ini kamu bisa menemukan area pedestrian yang cukup luas untuk menampung ribuan wisatawan sepanjang harinya.',
      scedule: '24 jam',
      ticket: 'free',
      photo: 'assets/img/titiknol.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2018/05/foto-titik-0-km-jogja-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2018/05/rute-menuju-titik-0-kilometer-jogja-451x257.jpg']
  ),

  Tourism(name : 'Museum History Of Java',
      address: 'Jl. Parangtritis km 5.5, Tarudan, Bangunharjo, Sewon, Bantul, Daerah Istimewa Yogyakarta.',
      description: 'Meskipun belum lama dibuka namun Museum History Of Java ini disebut – sebut sebagai salah satu museum terbaik di Yogyakarta, bahkan Menteri Kebudayaan Thailand Vira Rojpojchanarat dalam kunjungannya ke museum ini beberapa waktu yang lalu mengungkapkan kekagumannya terhadap museum ini. Vira Rojpojchanarat mengaku terpesona dengan bangunan serta koleksi yang dimiliki oleh Museum History Of Java ini.',
      scedule: '06.00-17.00',
      ticket: 'Rp. 30.000-Rp. 50.000',
      photo: 'assets/img/museum.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2019/08/Harga-Tiket-Masuk-Museum-History-Of-Java-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2019/08/Lokasi-Museum-History-Of-Java-451x257.jpg']
  ),

  Tourism(name : 'Plengkung Gading Jogja',
      address: ' Jl. Patehan Kidul No.4, Patehan, Kecamatan Kraton, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55133.',
      description: 'Plengkung gading ini adalah gapura atau pintu keluar maupun masuk yang menuju ke Ngayogyokarto Hadiningrat atau yang kerap dijukuki keraton Jogja. Siapa yag tidk kenal dengan kertaon Jogja, keraton ini adalah istana yang penuh dengan sejarah pada masa kepemimpinan Sultan Hamengkubuwono X, yang merupakan gubernur sekaligus raja di Yogyakarta.',
      scedule: '24 jam',
      ticket: 'free',
      photo: 'assets/img/plengku.jpg',
      imgurl: ['https://www.alodiatour.com/wp-content/uploads/2020/01/harga-tiket-masuk-plengkung-gading-jogja-451x257.jpg',
        'https://www.alodiatour.com/wp-content/uploads/2020/01/rute-menuju-plengkung-gading-jogja-451x257.jpg']
  )


];